version: 2.1
jobs:
    build:
        docker: 
            - image: alpine:latest
        steps:
            - run:
                  name: Zipping mod...
                  command: |
                    chmod +x ./.circleci/zipMod.sh
                    ./.circleci/zipMod.sh
                  shell: /bin/sh
